---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: nautible-aw
  namespace: nautible
webhooks:
- name: nautible-aw.nautible.com
  admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: <set your caBundle>
    service:
      name: nautible-ac
      namespace: nautible
      path: "/mutate"
  rules:
  - apiGroups: [""]
    apiVersions: ["v1"]
    operations: ["CREATE"]
    resources: ["pods"]
  sideEffects: None
  timeoutSeconds: 5
